//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyerShopAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public Nullable<int> TyerId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CustomerName { get; set; }
        public string TransactionDateTime { get; set; }
        public Nullable<int> CashRecieved { get; set; }
    
        public virtual Tyer Tyer { get; set; }
    }
}
