//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyerShopAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tyer()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int TyerId { get; set; }
        public string Brand { get; set; }
        public string Country { get; set; }
        public string Size { get; set; }
        public string Condition { get; set; }
        public Nullable<int> Purchase_Price { get; set; }
        public Nullable<int> Selling_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
